# - platform: xiaomi_miio
  # name: onkyo_plug
  # host: 192.168.0.39
  # token: 3279e9348fa2e170f918c9b418342dc8
# - platform: xiaomi_miio
  # name: room_plug
  # host: 192.168.0.238
  # token: 2d2f202164116eaa91c5883fca513b99
          
- platform: broadlink
  mac: 'ec:0b:ae:23:d4:04'
  # type: rm2
  switches:  
    - name: "bedroom"
      command_on: 'iMA2AbjtBAAaCBkIGggZCBoIGQkZCBkJGQkYCRkJBxoZCRgJGQoXChgJCBoHGggaCBkIGggZCAABBQgaGAkZCBkJGQgZCRkJGQgZCRkIGQkZCAgaGQkYCRkJGAkZCQgZCBoIGggZCBoHGggAAQUIGhgJGQkZCBkJGAkZCRkIGQkZCBkJGQkHGhkJGAkZCRkIGQkIGgcaCBoHGwcaCBoHAAEFCBoYChgJGQkYCRkIGQkZCBkJGQkYCRkJCBkZCRgLFwoYCRgKBxoIGgcbBxoHGwcaBwABBQgaGQkYCRkJGAkZCRkIGQkZCBkJGQgZCQgaGAkZCRgJGQkZCAgaCBkJGQgaCBkIGggAAQUIGRkJGQgZCRkJGAkZCBkJGQkYCRkJGQgIGhkIGQkZCBkJGQkIGQgaCBkIGggABdw='
      command_off: 'iAU0ABoJGQoaChoJGgkaCRoJGgkaCRoJGgkJGhoJGgkaCQkaCRoJGgkaCRoJGhkKGgoJAAEICRoAAAAA'
    - name: "lg_tv_power"
      command_on: 'JgBQAAABJpQTEhMSEjgSExITERQRFBITEzcROBEUETgTNxE4EjcTNxITERQROBITExMRFBE4ETgSOBI3ERQROBI4ETgTEhITEwAFKAABJkoSAA0FAAAAAAAAAAA=JgBQAAABJpQTEhMSEjgSExITERQRFBITEzcROBEUETgTNxE4EjcTNxITERQROBITExMRFBE4ETgSOBI3ERQROBI4ETgTEhITEwAFKAABJkoSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5QSExEUETgSExIUEhMSExITETgTNhIUETgSNxM3EjcROBI4EhMROBITEhMTEhI4EjcSExM3EhMSNxI3EzcSExEUEQAFKQABJksSAA0FAAAAAAAAAAA=JgBQAAABJ5QSExEUETgSExIUEhMSExITETgTNhIUETgSNxM3EjcROBI4EhMROBITEhMTEhI4EjcSExM3EhMSNxI3EzcSExEUEQAFKQABJksSAA0FAAAAAAAAAAA=JgBQAAABJ5QSExEUETgSExIUEhMSExITETgTNhIUETgSNxM3EjcROBI4EhMROBITEhMTEhI4EjcSExM3EhMSNxI3EzcSExEUEQAFKQABJksSAA0FAAAAAAAAAAA='
    - name: "ledbar_red"
      command_on: 'JgBYAAABKZUTExEUEhMTExEUERURFRAUEjgROBI4EjgRFBI4EjcSOBIUEhMRORITERQSFBEUEhMSOBE4ExQROBE4EjgSOBE4EgAFPAABKksRAAxTAAEpSxEADQU='
      command_off: 'JgBYAAABKZUTExEUEhMTExEUERURFRAUEjgROBI4EjgRFBI4EjcSOBIUEhMRORITERQSFBEUEhMSOBE4ExQROBE4EjgSOBE4EgAFPAABKksRAAxTAAEpSxEADQU='
    - name: "ledbar_blue"
      command_on: 'JgBYAAABKZYSExITEhQRFBITEhQRFRITETgSOBE4EjgRFBI3EjgTNxITEjgSOBEUEhMTExEVEhISOBIUEhMSOBE4EjgTNxE4EgAFOwABKUsSAAxGAAEpTBEADQU='
      command_off: 'JgBYAAABKZYSExITEhQRFBITEhQRFRITETgSOBE4EjgRFBI3EjgTNxITEjgSOBEUEhMTExEVEhISOBIUEhMSOBE4EjgTNxE4EgAFOwABKUsSAAxGAAEpTBEADQU='
    - name: "ledbar_green"
      command_on: 'JgBYAAABKZYSExITEhQRFRETEhQRFBITEjgTNxI4ETgSFBE4EjgTNxE4FBMQOBIUERQSExIVERMRFBM3ExMRORE4EjgROBI4EgAFOwABKksSAAxPAAEqShIADQU='
      command_off: 'JgBYAAABKZYSExITEhQRFRETEhQRFBITEjgTNxI4ETgSFBE4EjgTNxE4FBMQOBIUERQSExIVERMRFBM3ExMRORE4EjgROBI4EgAFOwABKksSAAxPAAEqShIADQU='
    - name: "ledbar_orange"
      command_on: 'JgBgAAABKpYRFBMTERQRFBMTEhMTEhIVEDgTNxI4EjgSFBE4ETgTNxMTERQSExI4ExMRFBITEhMTNxI4ETgTExE5ETgTNxI4EQAFQgABKksTAAxTAAEpSxIADFMAASpLEgANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKpYRFBMTERQRFBMTEhMTEhIVEDgTNxI4EjgSFBE4ETgTNxMTERQSExI4ExMRFBITEhMTNxI4ETgTExE5ETgTNxI4EQAFQgABKksTAAxTAAEpSxIADFMAASpLEgANBQAAAAAAAAAA'
    - name: "ledbar_yellow"
      command_on: 'JgBYAAABKZYSExIVEBUSEhIVEBQSFBEVETgROBI4EjgRFBM3EjcSOBM3ERQSFBE4EhQRFBEUEhQRFBE4EzcSFBI3EjgSNxI4EgAFQgABKUsSAAxTAAEpTBIADQU='
      command_off: 'JgBYAAABKZYSExIVEBUSEhIVEBQSFBEVETgROBI4EjgRFBM3EjcSOBM3ERQSFBE4EhQRFBEUEhQRFBE4EzcSFBI3EjgSNxI4EgAFQgABKUsSAAxTAAEpTBIADQU='  
    - name: "ledbar_puple"
      command_on: 'JgBQAAABK5QTEhMUEhMSFBITEhMTExITEzYUNhM3EzcTFBI3EzcTNhQSExMTNhMTEzcTExITExMSNxM3ExMTNhQTEjcTNxM3EwAFSQABK0kUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5QTEhMUEhMSFBITEhMTExITEzYUNhM3EzcTFBI3EzcTNhQSExMTNhMTEzcTExITExMSNxM3ExMTNhQTEjcTNxM3EwAFSQABK0kUAA0FAAAAAAAAAAA='  
    - name: "ledbar_music"
      command_on: 'JgBQAAABKZUTExEUEhMSFBITERQSExIUETgSOBE4EjgSFBE4EjgRORE4ETgSFBIUETgRFBEVERMSFBEUEjgROBIUETgSOBE4EgAFQQABKUsSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKZUTExEUEhMSFBITERQSExIUETgSOBE4EjgSFBE4EjgRORE4ETgSFBIUETgRFBEVERMSFBEUEjgROBIUETgSOBE4EgAFQQABKUsSAA0FAAAAAAAAAAA='  
    - name: "ledbar_cyan"
      command_on: 'JgBYAAABKpUSExITEhQRFBEUEhMSFBEUEjgSNxI4EjgRFBI4ETgSOBITEjgRFBM3ERQSFBEUERQSOBEUEjgRFBM3ETgSOBI4EQAFQQABKUsSAAwxAAEqSxEADQU='
      command_off: 'JgBYAAABKpUSExITEhQRFBEUEhMSFBEUEjgSNxI4EjgRFBI4ETgSOBITEjgRFBM3ERQSFBEUERQSOBEUEjgRFBM3ETgSOBI4EQAFQQABKUsSAAwxAAEqSxEADQU='  
    - name: "ledbar_white"
      command_on: 'JgBYAAABKZYSExITEhQSExITEhMSFBEUEzcROBM3EjcSFBE4EjgSOBE4EjgSNxMTEhMSFBEVEBQTEhIUEhMSNxI4EzcRORI3EwAFQAABKkoRAAxRAAEsShIADQU='
      command_off: 'JgBYAAABKZYSExITEhQSExITEhMSFBEUEzcROBM3EjcSFBE4EjgSOBE4EjgSNxMTEhMSFBEVEBQTEhIUEhMSNxI4EzcRORI3EwAFQAABKkoRAAxRAAEsShIADQU='        
    - name: "room3 light"
      command_on: 'sgCEAAojCyIiCwwiCyILIwsAAWAhDCIMCiMLIiIMCyILIiIMCyILIyEMIgsMIiIMIQwhDAsjCyILIwojIQwLIwsiCyMKAAFhIQwiDAojCyIiDAsiCyMhDAsjCiMhDCIMCiMiCyIMIQwLIwojCyMKIyILCyMLIgsjCgABYSEMIgwLIgsiFQAF3AAAAAA='
      command_off: 'sgg0ACUNDSQNJSUNJQ0MJQ0lDSUlDSUNJQ0kDQ0lJQ0MJQwlJQ0NJQ0AAXUNJQwlDCUkDQwlJQ0AAAAA'
    - name: "room3-2"
      command_on: 'sgCCACEMIgwKIwsjCyILIwsiIQ0KIwsjCgABYiEMIgwKIwsjIQwLIwojIgwLIgsjIQwhDQojIgwiCyIMCyILIwsiCyMKIyIMCyILIwsAAWEhDSEMCyMKIyILCyMLIyEMCyMLIiENIQwLIyEMIgwiCwsjCiQKIwsjCiMhDQojCyMKYwsABdwAAAAAAAA='
      command_off: 'sgY0AAwjDCMMIyMMDAABYiMNIwwMIwwjIwwMIwwjIwwMIwwjIwwjDAwkIwwjDCMMDCMMIwwjDCMAAAAA'
    - name: "my_room"
      command_on: 'sgc0ACMMIwwMIyMMIwwjDAwjDCIMIwwjIwwMIwwjDCMMAAFhIgwjDAwjDCIjDAwjDCMjDAwjDCMAAAAA'
      command_off: 'sgc0ACMNIgwMIwwjIwwMIwwjIgwMIwsjIgwjDAsjIgwjDCIMDCMMIwwjDCMMIwwjIwwMIwwAAWIAAAAA'
    - name: "room2 light"
      command_on: 'sgY0AAwlJA0lDQwkDSQNJQwAAXIMJQwkDSUkDQwkJA0kDQ0kDSUkDSQNDCUMJQwlJA0lDSUNJQ0AAAAA'
      command_off: 'sgg0AAwlDCYkDSQNJA0kDQwmJA4MJQwmJA0MJgwAAXUMJQwmDCUkDQwlJA0kDQwlDCUkDSQOCyYAAAAA'
    - name: "room2 fan"
      command_on: 'sgY0ACQNJA0kDQwlJA0MJSQNDCUNJQwAAXIMJQ0lDCQkDQwkJQ0kDQwlDCUkDSQNDCUMJQwlJA0AAAAA'
      command_off: 'sgAcAQsAAXIMJAwkDCQjDAwkJAwkDAwkDCQjDCQMDCQMJAwkIwwkDCQMJAwMJCQMCyQMJAwkJAwMAAFyDCQLJAwkJAwMJCMNJAwLJAwkJAwkDAwkDCMNIyQMJAwkDCQMDCQjDAwkDCQMJCQMDAABcgslDCQLJCQMDCQkDCMNCyQMJCQMJAwMJAwkCyQkDCQMJAwkDAwkJAwMJAskDCQkDAwAAXIMJAwkCyQkDAwkJAwkDAwkDCQjDCQNCyQMJAwkJAwjDSQMIw0LJCQMDCQMJAwkIw0LAAFzCyQMJAwkJAwMJCMNJAwLJAwkJAwkDAwkDCQLJCQNIwwkDCQMDCQkDAwkCyULJCQMDAABcgwkDCQMJCQMDCMkDCQMDCQMAAXcAAAAAAAAAAAAAAAA'
    - name: "genie remote"
      command_on: 'sjgWAAklCSYJJQklCQciZyJoImhlJQklCSUAAA=='
      command_off: 'sjgWAAklCSYJJQklCQciZyJoImhlJQklCSUAAA=='
    - name: "father remote"
      command_on: 'siYWACMMIwwKJCMMCiQKJAoGI2YjZ2YjImcAAA=='
      command_off: 'siYWACMMIwwKJCMMCiQKJAoGI2YjZ2YjImcAAA=='
    - name: "tv remote"
      command_on: 'siEWAAokIwwjDAoHI2dnIyNnI2gKJQolIwwAAA=='
      command_off: 'siEWAAokIwwjDAoHI2dnIyNnI2gKJQolIwwAAA=='
    - name: "desk_lamp"
      command_on: 'sgBuACIMCyMhDQsiCyMLIwsiDCILIwsiIgwMIgsjCyIiDAsjCyMhDCIMCwACuwsjCyIMIgsjCyIMIgsjCyMLIyEMDCILIyEMIgwLIyIMCyIMIgsjCyMLIgwiCyMiDAsiCyMLIyENCiMLIyENIQwLAAXcAAAAAAAAAAAAAA=='
      command_off: 'sgBSAQsjCiMLIwsjCiMLIwsjCyMhDAsjCyMhDCIMCyMhDQojCyMLIgwiCyMLIyENCiMLIwsjIQwiDAsjCyIiDAsjCwACZQsjDCILIwsiCyMLIwsiDCIMIiIMCyILIyIMIQwLIyIMCyMLIgsjCyMLIgwiIgwLIwsiDCIiDCENCyILIyILCyMLAAJmCyMLIwojCyMLIgsjCyMLIwsjIQwLIwsjIQwiDAsjIQ0LIgsjCyMKIwwiCyMhDAsjCyMLIyILIgwLIwsjIQwLIwsAAmYLIwsiCyMLIwsiCyMLIwsjCyIiDAsjCyIiDCIMCyIiDAwiCyMLIgsjDCILIyEMDCILIwsjIQwiDAsjCyMhDAsjCwACZgsjCyILIwsjCyILIwsjCyMLIiIMCyMLIyEMIgwLIiMLCyMMIgsiDCILIwsjIgsMIgsjCyMiCyIMDCILIiIMCyMLAAXcAAAAAAAA'      
    - name: "soudbar_mute"
      command_on: 'JgBQAAABJpUTNxI3EjgSNxI3FDYSExE4ExMRFBE4FBESFBE4FRASOBMSExIRFBM2FDYTEhQRFBEUNhQ1FDYTEhMSFDYTNhQ2EwAE2gABJ0oTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJpUTNxI3EjgSNxI3FDYSExE4ExMRFBE4FBESFBE4FRASOBMSExIRFBM2FDYTEhQRFBEUNhQ1FDYTEhMSFDYTNhQ2EwAE2gABJ0oTAA0FAAAAAAAAAAA='      
    - name: "spot_led_power"
      command_on: 'JgBYAAABMJQTFBISExQSExMSExQRFBIUETkROBI3FDYSFRE3EzcSOBM3EjcTFBISExQSEhMUERMSFBITEzgSNxM2EzgSNxI3EwAFPgABLUoTAAxLAAEsSxMADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgBYAAABLJUTExMSExMSFBEUEhQSFBEUEjcTNxM2FDYTFBI3EzYUNhMTEjcTFREUERQSFBMUEhMSNxMTEzYTNxM3EzcTNxI3FAAFMAABM0kUAAwfAAEsSxMADQUAAAAAAAAAAAAAAAAAAA=='     
    - name: "spot_led_flash"
      command_on: 'JgBYAAABK5QTExMSEhMUEhMSExMTExITEjcTNxM3EzYTExQ1EzcTNxM2EzcTEhM3ExITFBETEhUSEhIUEzYUEhM2EzcTNxM2EwAFMgABLkkTAAw8AAEuShMADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgBQAAABLZMTFBEUEhQSExMTEhITFBETEzcTNxI3EzcTExM2EzcTOBISExMSNxMSEzcSFBMSExITNxM3EhQSNxIUEzYTNxM2EwAFOQABLkkTAA0FAAAAAAAA'           
    - name: "spot_led_y"
      command_on: 'JgBQAAABLZMVERMTExIUEhMSFBITEhQSEzcUNhM3EzYUEhQ2FDYTNxMSFBITNhMTEzYUEhMSFBITNhU1FBITNxMSFDYTNhQ2EwAFOwABL0oTAA0FAAAAAAAA'
      command_off: 'JgBYAAABLJUTExMSExMSFBEUEhQSFBEUEjcTNxM2FDYTFBI3EzYUNhMTEjcTFREUERQSFBMUEhMSNxMTEzYTNxM3EzcTNxI3FAAFMAABM0kUAAwfAAEsSxMADQUAAAAAAAAAAAAAAAAAAA=='           
      
- platform: wake_on_lan
  mac: "74:56:3C:6B:F5:67"
  name: "computer"
  host : 192.168.0.3
  turn_off:
    service: shell_command.computer_off
- platform: wake_on_lan
  mac: "2C:4D:54:58:A7:CC"
  name: "woo_computer"
  host : 192.168.0.180
  turn_off:
    service: shell_command.woo_computer_off      
    
# - platform: circadian_lighting
#   lights_ct:
#     - light.jubang
#     - light.anbang

